add: modify pre-commit hook, avoid to commit development branch

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,3 +1,7 @@
 #!/bin/sh
 
-echo "hello from pre-commit"
+# developへのコミットを禁止する
+if [ "$CI_COMMIT_REF_NAME" = "develop" ]; then
+  echo "You cannot directly commit to the develop branch."
+  exit 1
+fi
